name: "Multi event Pipeline/ Workflow and pull_request closed"
on: 
    push: #Event: whenevr a push is made to the Master/ test
        branches:
            - master
            - test
    pull_request: #Event: whenevr a push is made to the repository
        branches:
            - master
        types:
            - closed
    workflow_dispatch: 



jobs:
    on-push:    #job name
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
          - name: "Running on  the Master/ Test push"
            run: echo "Running on  the Master/ Test push"
    
    on-pull_request:    #job name
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
         - name: "Running on the Master/Test pull"
           run: echo "Running on the Master/Test pull"
    
    on-pull_request_closed:    #job name
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        steps:
         - name: "Running on the  pull closed"
           run: echo "Running on the  pull closed"
           
    
    on-workflow-dispatch:    #job name
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:
         - name: "Running on workflow_dispatch"
           run: echo "Running on workflow_dispatch"